project:
  type: website
  output-dir : docs

website:
  title: "Tools for Survey-Based Prediction in ABCD"
  navbar:
    left:
      - file: index.qmd
        text: About - What is this?
      - file: faq.qmd
        text: FAQs
      - file: code-download.qmd
        text: Download the Code
      - file: metadata-download.qmd
        text: Download the Item Metadata
      - file: explore-metadata.qmd
        text: Explore the Item Metadata
      - file: worked-example.qmd
        text: Worked Example


      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

