project:
  type: website
  output-dir : docs

website:
  title: "The Pelham Lab's Predictive Screening Tools"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: metadata-download.qmd
        text: Metadata Download
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

